<%@ Page Language="C#" MasterPageFile="~/DefaultMaster.master" AutoEventWireup="true"
    CodeFile="NMItem_Master.aspx.cs" Inherits="Admin_NMItem_Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table align="left">
        <tr>
            <td>
                Non Mapics Items Maintainance
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td align="left" valign="top">
                <asp:GridView ID="gvNMItems" runat="server" AllowPaging="True" AutoGenerateColumns="False"
                    CellPadding="4" DataSourceID="NMItemSqlDataSource" DataKeyNames="NMItemID" ForeColor="#333333" GridLines="None"
                    ShowFooter="True">
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField DataField="NMItemId" ItemStyle-ForeColor="white"  />
                        <asp:BoundField DataField="ItemName" HeaderText="Item Number"  />
                        <asp:BoundField DataField="ItemDescription" HeaderText="Description" />
                    </Columns>
                    <RowStyle Font-Size="Small" BackColor="#EFF3FB" />
                    <EditRowStyle BackColor="#2461BF" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
            <td align="left" valign="top">
                <asp:DetailsView ID="dvNMItems" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False"
                    CellPadding="4" DataKeyNames="NMItemId" DataSourceID="dsDvNMItems" Font-Names="Verdana"
                    Font-Size="Small" Height="50px" Width="450px" 
                    ForeColor="#333333" GridLines="None" OnItemUpdated="dvNMItems_ItemUpdated" OnItemInserted="dvNMItems_ItemInserted" OnItemDeleted="dvNMItems_ItemDeleted">
                    <FooterStyle BackColor="#507CD1" ForeColor="White" Font-Bold="True" />
                    <EditRowStyle BackColor="#2461BF" />
                    <RowStyle BackColor="#EFF3FB" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <Fields>
                        <asp:TemplateField HeaderText="Id" InsertVisible="False">
                            <ItemTemplate>
                                <asp:Label ID="lblUserID" Text='<%# Eval("NMItemId") %>' runat="server"></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Non Mapics Item Number">
                            <InsertItemTemplate>
                                <asp:TextBox ID="txtNMItemName" Text='<%# Bind("ItemName") %>' runat="server"></asp:TextBox>
                                <br />
                                <asp:RequiredFieldValidator ID="rfvNMItemName" runat="server" ControlToValidate="txtNMItemName"
                                    ErrorMessage="Invalid"></asp:RequiredFieldValidator>
                            </InsertItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblNMItemName" Text='<%# Eval("ItemName") %>' runat="server"></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditNMItemName" runat="server" Text='<%# Bind("ItemName") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Description">
                            <InsertItemTemplate>
                                <asp:TextBox ID="txtItemDescription" TextMode="MultiLine" Text='<%# Bind("ItemDescription") %>'
                                    runat="server"></asp:TextBox>
                                <br />
                                <asp:RequiredFieldValidator ID="rfvItemDescription" runat="server" ErrorMessage="Invalid"
                                    ControlToValidate="txtItemDescription"></asp:RequiredFieldValidator>
                            </InsertItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblItemDescription" Text='<%# Eval("ItemDescription") %>' runat="server"></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditItemDescription" TextMode="MultiLine" runat="server" Text='<%# Bind("ItemDescription") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Fields>
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerSettings PageButtonCount="20" Mode="NumericFirstLast" />
                    <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
                    <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:DetailsView>
            </td>
        </tr>
        <tr>
            <td align="left" valign="top">
                <asp:SqlDataSource ID="NMItemSqlDataSource"  runat="server" ConnectionString="<%$ ConnectionStrings:PMSdbConnection %>"
                    InsertCommand="INSERT INTO tblNonMapicsItems(ItemName, ItemDescription) VALUES(@ItemName, @ItemDescription)"
                    ProviderName="<%$ ConnectionStrings:PMSdbConnection.ProviderName %>" SelectCommand="SELECT * FROM tblNonMapicsItems"
                    DeleteCommand="DELETE FROM tblNonMapicsItems WHERE NMItemId = @NMItemId " UpdateCommand="UPDATE tblNonMapicsItems SET ItemName = @ItemName, ItemDescription = @ItemDescription  WHERE NMItemId = @NMItemId">
                </asp:SqlDataSource>
                <asp:Button ID="btnAddNew" CssClass="button" Width="160px" runat="server" Text="ADD New Non-Mapics Item" OnClick="btnAddNew_Click" />
                <asp:SqlDataSource ID="dsDvNMItems" runat="server" ConnectionString="<%$ ConnectionStrings:PMSdbConnection %>"
                    InsertCommand="INSERT INTO tblNonMapicsItems(ItemName, ItemDescription) VALUES(@ItemName, @ItemDescription)"
                    ProviderName="<%$ ConnectionStrings:PMSdbConnection.ProviderName %>" SelectCommand="SELECT * FROM tblNonMapicsItems WHERE ([NMItemId] = @NMItemId)"
                    DeleteCommand="DELETE FROM tblNonMapicsItems WHERE NMItemId = @NMItemId " UpdateCommand="UPDATE tblNonMapicsItems SET ItemName = @ItemName, ItemDescription = @ItemDescription  WHERE NMItemId = @NMItemId">
                    <SelectParameters>
                        <asp:ControlParameter ControlID="gvNMItems" Name="NMItemId" PropertyName="SelectedValue"
                            Type="Int32" DefaultValue="0" />
                    </SelectParameters>
                </asp:SqlDataSource>
                &nbsp;
            </td>
            <td align="left" valign="top">
            </td>
        </tr>
    </table>
</asp:Content>
